import type { SummarySource, ToolRecommendation, UseCase } from "@/types";

export type AuditPdfPayload = {
  id: string;
  createdAt: string;
  toolCount: number;
  teamSize: number;
  useCase: UseCase;
  totalMonthlySpend: number;
  savingsPercent: number | null;
  totalMonthlySavings: number;
  totalAnnualSavings: number;
  isHighSavings: boolean;
  aiSummary: string;
  summarySource: SummarySource;
  recommendations: ToolRecommendation[];
};

const MARGIN = 48;
const PAGE_WIDTH = 612;
const CONTENT_WIDTH = PAGE_WIDTH - MARGIN * 2;
const LINE_HEIGHT = 14;

function wrapText(
  doc: import("jspdf").jsPDF,
  text: string,
  x: number,
  y: number,
  maxWidth: number,
  lineHeight: number
): number {
  const lines = doc.splitTextToSize(text, maxWidth) as string[];
  doc.text(lines, x, y);
  return y + lines.length * lineHeight;
}

export async function downloadAuditPdf(payload: AuditPdfPayload): Promise<void> {
  const { jsPDF } = await import("jspdf");
  const doc = new jsPDF({ unit: "pt", format: "letter" });
  let y = MARGIN;

  const addPageIfNeeded = (needed: number) => {
    if (y + needed > 756) {
      doc.addPage();
      y = MARGIN;
    }
  };

  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.text("SpendSense — AI Stack Audit Report", MARGIN, y);
  y += 28;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(100);
  const meta = `Report ID: ${payload.id} · ${new Date(payload.createdAt).toLocaleDateString("en-US", { dateStyle: "long" })} · ${payload.toolCount} tools · ${payload.teamSize}-person team · ${payload.useCase} use case`;
  y = wrapText(doc, meta, MARGIN, y, CONTENT_WIDTH, 12) + 8;
  doc.setTextColor(0);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.text(
    `Current spend: $${payload.totalMonthlySpend.toLocaleString()}/month`,
    MARGIN,
    y
  );
  y += 16;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.text("Potential savings", MARGIN, y);
  y += 16;
  doc.setFontSize(22);
  doc.text(
    payload.totalMonthlySavings > 0
      ? `$${payload.totalMonthlySavings.toLocaleString()}/month`
      : "Stack optimized",
    MARGIN,
    y
  );
  y += 22;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  if (payload.savingsPercent !== null) {
    doc.text(`Savings rate: ${payload.savingsPercent}% of current spend`, MARGIN, y);
    y += 14;
  }
  doc.text(
    `$${payload.totalAnnualSavings.toLocaleString()}/year annualized`,
    MARGIN,
    y
  );
  y += 24;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.text("Executive summary", MARGIN, y);
  y += 6;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(90);
  doc.text(
    payload.summarySource === "ai"
      ? "Generated by OpenAI"
      : "Rule-based summary",
    MARGIN,
    y
  );
  y += 14;
  doc.setTextColor(0);
  doc.setFontSize(10);
  addPageIfNeeded(80);
  y = wrapText(doc, payload.aiSummary, MARGIN, y, CONTENT_WIDTH, LINE_HEIGHT) + 20;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.text("Recommendations", MARGIN, y);
  y += 18;

  const sorted = [...payload.recommendations].sort(
    (a, b) => b.savings - a.savings
  );

  sorted.forEach((rec, i) => {
    addPageIfNeeded(72);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.text(`${i + 1}. ${rec.toolName}`, MARGIN, y);
    y += 14;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(80);
    y = wrapText(
      doc,
      `${rec.currentPlan} · $${rec.currentSpend}/mo → ${rec.recommendedAction}`,
      MARGIN,
      y,
      CONTENT_WIDTH,
      12
    );
    if (rec.savings > 0) {
      doc.setTextColor(30, 120, 60);
      y = wrapText(
        doc,
        `Save $${rec.savings}/mo · $${rec.annualSavings}/yr`,
        MARGIN,
        y,
        CONTENT_WIDTH,
        12
      );
      doc.setTextColor(0);
    }
    y = wrapText(doc, rec.reason, MARGIN, y, CONTENT_WIDTH, LINE_HEIGHT) + 14;
  });

  if (payload.isHighSavings) {
    addPageIfNeeded(40);
    doc.setFont("helvetica", "italic");
    doc.setFontSize(9);
    doc.setTextColor(80);
    y = wrapText(
      doc,
      "High-savings audit: Credex may help capture additional savings through discounted AI infrastructure credits.",
      MARGIN,
      y,
      CONTENT_WIDTH,
      12
    );
  }

  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(120);
  const footerY = 756;
  doc.text(
    "Numbers from SpendSense rule-based audit · spendsense.app",
    MARGIN,
    footerY
  );

  doc.save(`spendsense-audit-${payload.id}.pdf`);
}
