import { ArrowRight, Sparkles } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Separator } from "@/components/ui/separator";
import type { RecommendationType, ToolRecommendation } from "@/types";

const TYPE_LABELS: Record<RecommendationType, string> = {
  downgrade: "Downgrade",
  "switch-tool": "Alternative",
  "optimize-seats": "Seats",
  "right-sized": "Optimal",
  "use-credits": "Credits",
};

interface AuditResultsProps {
  recommendations: ToolRecommendation[];
  aiSummary: string;
}

export default function AuditResults({
  recommendations,
  aiSummary,
}: AuditResultsProps) {
  return (
    <div className="space-y-4">
      {recommendations.map((rec) => (
        <Card
          key={`${rec.tool}-${rec.currentPlan}`}
          size="sm"
          className={`rounded-xl border-stone-200 ${rec.savings > 0 ? "border-primary/30 bg-accent/20" : ""}`}
        >
          <CardHeader className="flex flex-row items-start justify-between gap-2 pb-2">
            <div>
              <CardTitle className="text-base">{rec.toolName}</CardTitle>
              <CardDescription className="capitalize">
                {rec.currentPlan} · ${rec.currentSpend}/mo
              </CardDescription>
            </div>
            <Badge variant={rec.savings > 0 ? "default" : "secondary"}>
              {TYPE_LABELS[rec.recommendationType]}
            </Badge>
          </CardHeader>
          <CardContent className="space-y-3">
            <div className="flex flex-col gap-2 text-sm sm:flex-row sm:items-center">
              <span className="flex-1 rounded-lg bg-stone-100 px-3 py-2 capitalize text-muted-foreground">
                {rec.currentPlan}
              </span>
              <ArrowRight className="hidden h-4 w-4 shrink-0 text-primary sm:block" />
              <span
                className={`flex-1 rounded-lg px-3 py-2 font-medium ${
                  rec.savings > 0
                    ? "bg-primary/10 text-primary"
                    : "bg-stone-100 text-foreground"
                }`}
              >
                {rec.recommendedAction}
              </span>
            </div>
            {rec.savings > 0 && (
              <p className="text-sm font-semibold text-primary">
                Save ${rec.savings}/mo · ${rec.annualSavings}/yr
              </p>
            )}
            <p className="text-sm leading-relaxed text-muted-foreground">
              {rec.reason}
            </p>
          </CardContent>
        </Card>
      ))}

      <Separator className="my-6" />

      <Card className="rounded-xl border-stone-200">
        <CardHeader>
          <div className="flex items-center gap-2">
            <Sparkles className="h-4 w-4 text-primary" />
            <CardTitle className="text-base">Personalized summary</CardTitle>
          </div>
          <Badge variant="outline" className="w-fit border-primary/30 text-primary">
            Generated by Claude
          </Badge>
        </CardHeader>
        <CardContent>
          <p className="leading-relaxed text-muted-foreground">{aiSummary}</p>
        </CardContent>
      </Card>
    </div>
  );
}
